'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let current=[],paths=[],selected=null,replayRunning=false,livePolling=true,busy=false,latest=null,metricsReady=false;
const colors={low:'#198038',medium:'#b28600',high:'#da1e28',unknown:'#6f6f6f'};
const labels={low:'Низкий риск',medium:'Наблюдение',high:'Высокий риск',unknown:'Нет прогноза'};
const fmt=n=>n==null?'—':`${n>=0?'+':''}${Math.round(n)} с`;
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const moscow=value=>value?new Date(value).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const sourceLabel=value=>value==='live'?'NDTP live':value==='historical_replay'?'Replay':value==='api'?'API':'—';
const ageLabel=value=>{if(!value)return'—';if(mode()==='replay')return moscow(new Date(Number(value)*1000));const seconds=Math.max(0,Math.round(Date.now()/1000-Number(value)));return seconds<2?'только что':seconds<60?`${seconds} с назад`:`${Math.floor(seconds/60)} мин назад`};
async function api(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`${response.status}: ${(await response.text()).slice(0,180)}`);return response.json()}
function svgEl(name,attrs,parent=$('map')){const node=document.createElementNS(NS,name);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,value);parent.appendChild(node);return node}
window.TransitMap.mount(id=>choose(id));
function mode(){return $('mode').value}
function setConnected(ok){$('connection-dot').className=`connection-dot ${ok?'ok':'error'}`;$('connection-label').textContent=ok?'Backend API на связи':'Нет связи с Backend API';$('backend-dot').className=`service-dot ${ok?'ok':'error'}`;$('backend-status').textContent=ok?'на связи':'недоступен'}
function updateControls(){const live=mode()==='live';$('mode-label').textContent=live?'ЖИВОЙ ПОТОК NDTP':'ИСТОРИЧЕСКИЙ REPLAY';$('clock-caption').textContent=live?'Московское время потока':'Время исторических данных';$('step').textContent=live?'Обновить сейчас':'Следующая точка';$('play').textContent=live?(livePolling?'Приостановить мониторинг':'Возобновить мониторинг'):(replayRunning?'Пауза':'Запустить автопрогон');$('status').textContent=live?(livePolling?'Мониторинг live-потока':'Мониторинг приостановлен'):(replayRunning?'Автопрогон выполняется':latest?.state?.index?'Replay готов к продолжению':'Replay готов к запуску');$('status-mark').className=`status-mark ${(live&&!livePolling)||(!live&&!replayRunning)?'paused':''}`}
function advisory(data){const live=data.state.mode==='live',vehicles=data.vehicles||[],packets=data.counters.ndtp_packets||0,hasPrediction=vehicles.some(v=>v.prediction_s!=null);$('advisory').className='advisory info';if(live&&packets){$('notice-title').textContent='Живой NDTP-поток активен';$('notice').textContent=hasPrediction?'Телеметрия поступает, прогнозы рассчитываются по актуальным событиям.':'Телеметрия поступает. Прогноз появится, когда для ТС найдётся плановая остановка в окне 10–15 минут.'}else if(live){$('notice-title').textContent='Ожидание NDTP-пакетов';$('notice').textContent='Эмулятор должен отправлять пакеты на TCP 9201. Проверьте контейнер emulator и его конфигурацию.';$('advisory').className='advisory warning'}else{$('notice-title').textContent='Исторический replay';$('notice').textContent='Данные за 6 января 2026 года. Используйте следующую точку или автопрогон; это не текущая дорожная ситуация.'}$('last-update').textContent=`Обновлено ${new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`}
function draw(){window.TransitMap.render(current,paths,selected)}
function choose(id){selected=id;draw();renderDetail();renderTable();window.TransitMap.focus(id)}
function renderDetail(){const vehicle=current.find(v=>v.tr_id===selected);if(!vehicle){$('detail').className='detail empty-detail';$('detail').innerHTML='<div class="empty-symbol">＋</div><h3>Выберите транспорт</h3><p>Нажмите на маркер или строку таблицы, чтобы увидеть телеметрию и прогноз.</p>';return}$('detail').className='detail';const prediction=vehicle.prediction_s==null?'—':fmt(vehicle.prediction_s);const interval=vehicle.lower_s==null?'—':`${fmt(vehicle.lower_s)} … ${fmt(vehicle.upper_s)}`;$('detail').innerHTML=`<div class="detail-top"><div><p class="section-label">ТРАНСПОРТНОЕ СРЕДСТВО</p><h3>ТС ${esc(vehicle.tr_id)}</h3></div><span class="tag ${esc(vehicle.level)}">${labels[vehicle.level]}</span></div><div class="forecast">${prediction}</div><p>${vehicle.prediction_s==null?'Прогноз пока не построен':'Прогноз отклонения от расписания'}</p><div class="detail-grid"><div><span>ИСТОЧНИК</span><b>${sourceLabel(vehicle.source)}</b></div><div><span>ПОСЛЕДНЯЯ ТЕЛЕМЕТРИЯ</span><b>${ageLabel(vehicle.position_time)}</b></div><div><span>ЦЕЛЕВАЯ ОСТАНОВКА</span><b>${esc(vehicle.stop_address)}</b></div><div><span>ПЛАНОВОЕ ПРИБЫТИЕ</span><b>${moscow(vehicle.target_time_begin)}</b></div><div><span>90% ИНТЕРВАЛ</span><b>${interval}</b></div><div><span>РИСК &gt;120 С</span><b>${vehicle.late_probability==null?'—':Math.round(vehicle.late_probability*100)+'%'}</b></div></div><div class="reason-box"><b>Статус:</b> ${esc(vehicle.reason||'Данные получены, анализ продолжается')}</div><div class="coords">${Number.isFinite(vehicle.lat)?`${vehicle.lat.toFixed(6)}, ${vehicle.lon.toFixed(6)}`:'Координаты отсутствуют'} · ${esc(vehicle.model||'без модели')}</div>`}
function filteredVehicles(){const query=$('vehicle-search').value.trim();return current.filter(v=>(!$('risk-only').checked||v.level==='high')&&(!query||String(v.tr_id).includes(query)))}
function renderTable(){const rows=filteredVehicles();$('rows').innerHTML=rows.length?rows.map(v=>`<tr data-id="${v.tr_id}" class="${selected===v.tr_id?'selected':''}"><td><b>ТС ${v.tr_id}</b></td><td><span class="source">${sourceLabel(v.source)}</span></td><td><span class="tag ${v.level}">${labels[v.level]}</span></td><td>${ageLabel(v.position_time||v.T)}</td><td>${esc(v.stop_address)}</td><td><b>${fmt(v.prediction_s)}</b></td><td class="reason-cell">${esc(v.reason)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty-row">Нет транспорта, соответствующего фильтру.</td></tr>';for(const row of $('rows').querySelectorAll('[data-id]'))row.onclick=()=>choose(Number(row.dataset.id))}
function render(data){latest=data;current=[...(data.vehicles||[])];const priority={high:0,medium:1,low:2,unknown:3};current.sort((a,b)=>(priority[a.level]??9)-(priority[b.level]??9));if(!current.some(v=>v.tr_id===selected))selected=current[0]?.tr_id??null;const counters=data.counters||{},live=data.state.mode==='live';$('mode').value=data.state.mode;$('clock').textContent=data.state.clock?moscow(data.state.clock):live?new Date().toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow'}):'—';$('progress').textContent=live?`${counters.ndtp_packets||0} пакетов принято`:`${data.state.index} / ${data.total_points} точек`;$('total').textContent=current.length;$('total-note').textContent=current.length?`${current.filter(v=>v.source==='live').length} из живого потока`:'Нет активных ТС';$('packets').textContent=counters.ndtp_packets||0;$('telemetry').textContent=`${counters.telemetry_rows||0} строк телеметрии`;$('predictions').textContent=counters.predictions||0;$('latency').textContent=counters.last_inference_ms==null?'ML-запрос —':`Последний ML-запрос ${Math.round(counters.last_inference_ms)} мс`;$('high').textContent=current.filter(v=>v.level==='high').length;$('issues').textContent=`Ошибок сопоставления: ${counters.unknown_units||0}`;$('ndtp-dot').className=`service-dot ${live&&counters.ndtp_packets?'ok':live?'warn':'idle'}`;$('ndtp-status').textContent=live?(counters.ndtp_packets?`${counters.ndtp_packets} пакетов принято`:'ожидание пакетов'):'не используется в replay';$('ml-dot').className=`service-dot ${metricsReady?'ok':'warn'}`;$('ml-status').textContent=metricsReady?'модель и метрики загружены':'проверка модели';$('status').textContent=live?(livePolling?'Мониторинг live-потока':'Мониторинг приостановлен'):(replayRunning?'Автопрогон выполняется':data.state.index?'Replay готов к продолжению':'Replay готов к запуску');advisory(data);updateControls();draw();renderDetail();renderTable()}

function renderIncidents(data){const items=data.items||[];$('incident-summary').textContent=items.length;$('incident-detail').textContent=items.length?`Последний расчёт: ${moscow(data.as_of)}`:'Высокий и средний риск';$('incident-list').innerHTML=items.length?items.map(v=>`<button class="incident-row" data-id="${v.vehicle_id}"><span class="tag ${v.level}">${labels[v.level]}</span><b>ТС ${v.vehicle_id}</b><span>${v.prediction_s==null?'—':fmt(v.prediction_s)}</span><span>${esc(v.reason||'Требуется проверка')}</span></button>`).join(''):'<span class="empty-row">Нет активных инцидентов.</span>';for(const row of $('incident-list').querySelectorAll('[data-id]'))row.onclick=()=>choose(Number(row.dataset.id))}
async function refreshRisk(){try{const [risk,incident]=await Promise.all([api('/api/risk'),api('/api/incidents')]);renderRisk(risk);renderIncidents(incident)}catch(error){$('risk-detail').textContent='API риска недоступен'}}
async function runWhatIf(){const body={extra_vehicles:Number($('what-if-vehicles').value||0),headway_reduction_pct:Number($('what-if-headway').value||0)};try{const data=await api('/api/what-if',body);const high=data.projected.filter(x=>x.projected_level==='high').length;const medium=data.projected.filter(x=>x.projected_level==='medium').length;$('what-if-result').textContent=`${high} красных · ${medium} жёлтых`;$('what-if-note').textContent=`Множитель риска ${data.assumptions.risk_multiplier.toFixed(2)}; сценарий не изменяет live-поток`}catch(error){$('what-if-result').textContent='Ошибка расчёта';$('what-if-note').textContent=error.message}}
$('what-if-run').onclick=runWhatIf;
function renderRisk(data){const routes=data.routes||[];$('risk-summary').textContent=routes.length?`${data.high_routes||0} красных · ${data.medium_routes||0} жёлтых`:'Нет активных маршрутов';$('risk-detail').textContent=routes.length?routes.map(r=>`ТС ${r.tr_id}: ${labels[r.level]}`).join(' · '):'—';$('route-updated').textContent=data.as_of?moscow(data.as_of):'—';$('route-cards').innerHTML=routes.length?routes.map(r=>{const probability=r.max_late_probability==null?'—':`${Math.round(r.max_late_probability*100)}%`;return `<div class="route-card ${r.level}"><div class="route-card-top"><b>Маршрут ${esc(r.tr_id)}</b><span class="tag ${r.level}">${labels[r.level]}</span></div><div class="route-card-value">${probability}</div><div class="route-card-meta"><span>${r.vehicle_count} ТС в потоке</span><span>${r.high_count} требуют внимания</span></div><div class="route-meter"><i style="width:${r.max_late_probability==null?0:Math.min(100,r.max_late_probability*100)}%"></i></div></div>`}).join(''):'<div class="empty-row">Нет активных маршрутов.</div>'}
function renderMetrics(data){const v=data.v5||{};$('model-pill').textContent=`${String(v.model||'v5').toUpperCase()} · ${v.features||'—'} признака`;$('ml-mae').textContent=v.mae_s==null?'—':`${v.mae_s.toFixed(1)} с`;$('ml-baseline').textContent=v.baseline_mae_s==null?'—':`${v.baseline_mae_s.toFixed(1)} с`;$('ml-improvement').textContent=v.improvement_pct==null?'—':`${v.improvement_pct.toFixed(1)}%`;$('ml-coverage').textContent=v.coverage==null?'—':`${(v.coverage*100).toFixed(1)}%`;$('ml-points').textContent=v.test_points==null?'—':Number(v.test_points).toLocaleString('ru-RU');$('ml-latency').textContent=v.batch_inference_ms==null?'—':`${Number(v.batch_inference_ms).toFixed(1)} мс`;$('mae').textContent=v.mae_s==null?'—':`${v.mae_s.toFixed(1)} с`;$('baseline').textContent=v.baseline_mae_s==null?'—':`${v.baseline_mae_s.toFixed(1)} с`;const items=data.feature_importance||[],max=Number(items[0]?.importance||1);$('feature-bars').innerHTML=items.map(item=>`<div class="feature-row"><span title="${esc(item.feature)}">${esc(item.feature.replace(/^route_/,'route · '))}</span><i><b style="width:${Math.min(100,Number(item.importance)/max*100)}%"></b></i><em>${Number(item.importance).toFixed(1)}</em></div>`).join('')||'<div class="empty-row">Нет данных о признаках</div>'}
async function refreshRisk(){try{const [risk,incident]=await Promise.all([api('/api/risk'),api('/api/incidents')]);renderRisk(risk);renderIncidents(incident)}catch(error){$('risk-detail').textContent='API риска недоступен'}}

async function refresh(){try{const data=await api('/api/state');setConnected(true);render(data);await refreshRisk()}catch(error){setConnected(false);$('status').textContent='Связь с API потеряна';$('status-mark').className='status-mark error';$('advisory').className='advisory error';$('notice-title').textContent='Backend недоступен';$('notice').textContent=error.message}}

async function stepReplay(){if(busy)return;busy=true;try{const result=await api('/api/replay/step',{});if(result.done){replayRunning=false;$('status').textContent='Исторический прогон завершён'}await refresh()}catch(error){replayRunning=false;$('notice').textContent=error.message}finally{busy=false;updateControls()}}
$('step').onclick=()=>mode()==='live'?refresh():stepReplay();
$('play').onclick=()=>{if(mode()==='live'){livePolling=!livePolling;if(livePolling)refresh()}else{replayRunning=!replayRunning;if(replayRunning)stepReplay()}updateControls()};
$('mode').onchange=async()=>{replayRunning=false;livePolling=true;busy=false;selected=null;try{await api('/api/mode',{mode:mode()});await refresh()}catch(error){$('notice').textContent=error.message}updateControls()};
$('risk-only').onchange=renderTable;$('vehicle-search').oninput=renderTable;
setInterval(()=>{$('wall-clock').textContent=new Date().toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow'});if(mode()==='replay'&&replayRunning)stepReplay();else if(mode()==='live'&&livePolling)refresh()},3000);
(async()=>{try{const [network,metrics]=await Promise.all([api('/api/network'),api('/api/metrics')]);paths=network.paths||[];metricsReady=true;renderMetrics(metrics);$('mae').textContent=`${metrics.v5?.mae_s?.toFixed(1)||metrics.test_mae_s.toFixed(1)} с`;$('baseline').textContent=`${metrics.v5?.baseline_mae_s?.toFixed(1)||metrics.persistence_mae_s.toFixed(1)} с`;await refresh()}catch(error){$('notice').textContent=error.message;await refresh()}})();
updateControls();$('wall-clock').textContent=new Date().toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow'});
