'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let current=[],paths=[],selected=null,replayRunning=false,livePolling=true,busy=false,latest=null,metricsReady=false;
const colors={low:'#198038',medium:'#b28600',high:'#da1e28',unknown:'#6f6f6f'};
const labels={low:'Низкий риск',medium:'Наблюдение',high:'Высокий риск',unknown:'Нет прогноза'};
const fmt=n=>n==null?'—':`${n>=0?'+':''}${Math.round(n)} с`;
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const moscow=value=>value?new Date(value).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const sourceLabel=value=>value==='live'?'NDTP live':value==='historical_replay'?'Replay':value==='api'?'API':'—';
const ageLabel=value=>{if(!value)return'—';const seconds=Math.max(0,Math.round(Date.now()/1000-Number(value)));return seconds<2?'только что':seconds<60?`${seconds} с назад`:`${Math.floor(seconds/60)} мин назад`};
async function api(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`${response.status}: ${(await response.text()).slice(0,180)}`);return response.json()}
function svgEl(name,attrs,parent=$('map')){const node=document.createElementNS(NS,name);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,value);parent.appendChild(node);return node}
function mode(){return $('mode').value}
function setConnected(ok){$('connection-dot').className=`connection-dot ${ok?'ok':'error'}`;$('connection-label').textContent=ok?'Backend API на связи':'Нет связи с Backend API';$('backend-dot').className=`service-dot ${ok?'ok':'error'}`;$('backend-status').textContent=ok?'на связи':'недоступен'}
function updateControls(){const live=mode()==='live';$('mode-label').textContent=live?'ЖИВОЙ ПОТОК NDTP':'ИСТОРИЧЕСКИЙ REPLAY';$('clock-caption').textContent=live?'Московское время потока':'Время исторических данных';$('step').textContent=live?'Обновить сейчас':'Следующая точка';$('play').textContent=live?(livePolling?'Приостановить мониторинг':'Возобновить мониторинг'):(replayRunning?'Пауза':'Запустить автопрогон');$('status').textContent=live?(livePolling?'Мониторинг live-потока':'Мониторинг приостановлен'):(replayRunning?'Автопрогон выполняется':latest?.state?.index?'Replay готов к продолжению':'Replay готов к запуску');$('status-mark').className=`status-mark ${(live&&!livePolling)||(!live&&!replayRunning)?'paused':''}`}
function advisory(data){const live=data.state.mode==='live',vehicles=data.vehicles||[],packets=data.counters.ndtp_packets||0,hasPrediction=vehicles.some(v=>v.prediction_s!=null);$('advisory').className='advisory info';if(live&&packets){$('notice-title').textContent='Живой NDTP-поток активен';$('notice').textContent=hasPrediction?'Телеметрия поступает, прогнозы рассчитываются по актуальным событиям.':'Телеметрия поступает. Прогноз появится, когда для ТС найдётся плановая остановка в окне 10–15 минут.'}else if(live){$('notice-title').textContent='Ожидание NDTP-пакетов';$('notice').textContent='Эмулятор должен отправлять пакеты на TCP 9201. Проверьте контейнер emulator и его конфигурацию.';$('advisory').className='advisory warning'}else{$('notice-title').textContent='Исторический replay';$('notice').textContent='Данные за 6 января 2026 года. Используйте следующую точку или автопрогон; это не текущая дорожная ситуация.'}$('last-update').textContent=`Обновлено ${new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`}
function draw(){const svg=$('map');svg.replaceChildren();const ids=new Set(current.map(v=>v.tr_id));const relevant=paths.filter(path=>ids.has(path.tr_id));const positioned=current.filter(v=>Number.isFinite(v.lon)&&Number.isFinite(v.lat));const all=relevant.flatMap(path=>path.points).concat(positioned.map(v=>[v.lon,v.lat])).filter(point=>Number.isFinite(point[0])&&Number.isFinite(point[1]));$('map-empty').classList.toggle('show',!all.length);if(!all.length)return;const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);if(maxX-minX<.02){minX-=.01;maxX+=.01}if(maxY-minY<.02){minY-=.01;maxY+=.01}const x=value=>55+(value-minX)/(maxX-minX)*790,y=value=>415-(value-minY)/(maxY-minY)*360;for(let i=0;i<6;i++){svgEl('line',{x1:55+i*158,y1:35,x2:55+i*158,y2:425,stroke:'#e0e0e0','stroke-width':1});svgEl('line',{x1:45,y1:55+i*72,x2:855,y2:55+i*72,stroke:'#e0e0e0','stroke-width':1})}for(const path of relevant){const vehicle=current.find(v=>v.tr_id===path.tr_id);svgEl('polyline',{points:path.points.map(p=>`${x(p[0])},${y(p[1])}`).join(' '),fill:'none',stroke:vehicle?colors[vehicle.level]:'#8d8d8d','stroke-width':vehicle?3:1,opacity:vehicle?.65:.2});if(path.points.length){const label=svgEl('text',{x:x(path.points[0][0])+8,y:y(path.points[0][1])-8,class:'route-label'});label.textContent=`ТС ${path.tr_id}`}}for(const vehicle of positioned){const group=svgEl('g',{class:'vehicle',tabindex:0,role:'button','aria-label':`ТС ${vehicle.tr_id}, ${labels[vehicle.level]}`});svgEl('circle',{cx:x(vehicle.lon),cy:y(vehicle.lat),r:18,fill:colors[vehicle.level],class:'pulse'},group);svgEl('circle',{cx:x(vehicle.lon),cy:y(vehicle.lat),r:selected===vehicle.tr_id?12:9,fill:colors[vehicle.level],stroke:'#fff','stroke-width':4},group);const title=svgEl('title',{},group);title.textContent=`ТС ${vehicle.tr_id} · ${labels[vehicle.level]}`;group.addEventListener('click',()=>choose(vehicle.tr_id));group.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(vehicle.tr_id)}})}}
function choose(id){selected=id;draw();renderDetail();renderTable()}
function renderDetail(){const vehicle=current.find(v=>v.tr_id===selected);if(!vehicle){$('detail').className='detail empty-detail';$('detail').innerHTML='<div class="empty-symbol">＋</div><h3>Выберите транспорт</h3><p>Нажмите на маркер или строку таблицы, чтобы увидеть телеметрию и прогноз.</p>';return}$('detail').className='detail';const prediction=vehicle.prediction_s==null?'—':fmt(vehicle.prediction_s);const interval=vehicle.lower_s==null?'—':`${fmt(vehicle.lower_s)} … ${fmt(vehicle.upper_s)}`;$('detail').innerHTML=`<div class="detail-top"><div><p class="section-label">ТРАНСПОРТНОЕ СРЕДСТВО</p><h3>ТС ${esc(vehicle.tr_id)}</h3></div><span class="tag ${esc(vehicle.level)}">${labels[vehicle.level]}</span></div><div class="forecast">${prediction}</div><p>${vehicle.prediction_s==null?'Прогноз пока не построен':'Прогноз отклонения от расписания'}</p><div class="detail-grid"><div><span>ИСТОЧНИК</span><b>${sourceLabel(vehicle.source)}</b></div><div><span>ПОСЛЕДНЯЯ ТЕЛЕМЕТРИЯ</span><b>${ageLabel(vehicle.position_time)}</b></div><div><span>ЦЕЛЕВАЯ ОСТАНОВКА</span><b>${esc(vehicle.stop_address)}</b></div><div><span>ПЛАНОВОЕ ПРИБЫТИЕ</span><b>${moscow(vehicle.target_time_begin)}</b></div><div><span>90% ИНТЕРВАЛ</span><b>${interval}</b></div><div><span>РИСК &gt;120 С</span><b>${vehicle.late_probability==null?'—':Math.round(vehicle.late_probability*100)+'%'}</b></div></div><div class="reason-box"><b>Статус:</b> ${esc(vehicle.reason||'Данные получены, анализ продолжается')}</div><div class="coords">${Number.isFinite(vehicle.lat)?`${vehicle.lat.toFixed(6)}, ${vehicle.lon.toFixed(6)}`:'Координаты отсутствуют'} · ${esc(vehicle.model||'без модели')}</div>`}
function filteredVehicles(){const query=$('vehicle-search').value.trim();return current.filter(v=>(!$('risk-only').checked||v.level==='high')&&(!query||String(v.tr_id).includes(query)))}
function renderTable(){const rows=filteredVehicles();$('rows').innerHTML=rows.length?rows.map(v=>`<tr data-id="${v.tr_id}" class="${selected===v.tr_id?'selected':''}"><td><b>ТС ${v.tr_id}</b></td><td><span class="source">${sourceLabel(v.source)}</span></td><td><span class="tag ${v.level}">${labels[v.level]}</span></td><td>${ageLabel(v.position_time||v.T)}</td><td>${esc(v.stop_address)}</td><td><b>${fmt(v.prediction_s)}</b></td><td class="reason-cell">${esc(v.reason)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty-row">Нет транспорта, соответствующего фильтру.</td></tr>';for(const row of $('rows').querySelectorAll('[data-id]'))row.onclick=()=>choose(Number(row.dataset.id))}
function render(data){latest=data;current=[...(data.vehicles||[])];const priority={high:0,medium:1,low:2,unknown:3};current.sort((a,b)=>(priority[a.level]??9)-(priority[b.level]??9));if(!current.some(v=>v.tr_id===selected))selected=current[0]?.tr_id??null;const counters=data.counters||{},live=data.state.mode==='live';$('mode').value=data.state.mode;$('clock').textContent=data.state.clock?moscow(data.state.clock):live?new Date().toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow'}):'—';$('progress').textContent=live?`${counters.ndtp_packets||0} пакетов принято`:`${data.state.index} / ${data.total_points} точек`;$('total').textContent=current.length;$('total-note').textContent=current.length?`${current.filter(v=>v.source==='live').length} из живого потока`:'Нет активных ТС';$('packets').textContent=counters.ndtp_packets||0;$('telemetry').textContent=`${counters.telemetry_rows||0} строк телеметрии`;$('predictions').textContent=counters.predictions||0;$('latency').textContent=counters.last_inference_ms==null?'ML-запрос —':`Последний ML-запрос ${Math.round(counters.last_inference_ms)} мс`;$('high').textContent=current.filter(v=>v.level==='high').length;$('issues').textContent=`Ошибок сопоставления: ${counters.unknown_units||0}`;$('ndtp-dot').className=`service-dot ${live&&counters.ndtp_packets?'ok':live?'warn':'idle'}`;$('ndtp-status').textContent=live?(counters.ndtp_packets?`${counters.ndtp_packets} пакетов принято`:'ожидание пакетов'):'не используется в replay';$('ml-dot').className=`service-dot ${metricsReady?'ok':'warn'}`;$('ml-status').textContent=metricsReady?'модель и метрики загружены':'проверка модели';$('status').textContent=live?(livePolling?'Мониторинг live-потока':'Мониторинг приостановлен'):(replayRunning?'Автопрогон выполняется':data.state.index?'Replay готов к продолжению':'Replay готов к запуску');advisory(data);updateControls();draw();renderDetail();renderTable()}
async function refresh(){try{const data=await api('/api/state');setConnected(true);render(data)}catch(error){setConnected(false);$('status').textContent='Связь с API потеряна';$('status-mark').className='status-mark error';$('advisory').className='advisory error';$('notice-title').textContent='Backend недоступен';$('notice').textContent=error.message}}
async function stepReplay(){if(busy)return;busy=true;try{const result=await api('/api/replay/step',{});if(result.done){replayRunning=false;$('status').textContent='Исторический прогон завершён'}await refresh()}catch(error){replayRunning=false;$('notice').textContent=error.message}finally{busy=false;updateControls()}}
$('step').onclick=()=>mode()==='live'?refresh():stepReplay();
$('play').onclick=()=>{if(mode()==='live'){livePolling=!livePolling;if(livePolling)refresh()}else{replayRunning=!replayRunning;if(replayRunning)stepReplay()}updateControls()};
$('mode').onchange=async()=>{replayRunning=false;livePolling=true;busy=false;selected=null;try{await api('/api/mode',{mode:mode()});await refresh()}catch(error){$('notice').textContent=error.message}updateControls()};
$('risk-only').onchange=renderTable;$('vehicle-search').oninput=renderTable;
setInterval(()=>{$('wall-clock').textContent=new Date().toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow'});if(mode()==='replay'&&replayRunning)stepReplay();else if(mode()==='live'&&livePolling)refresh()},3000);
(async()=>{try{const [network,metrics]=await Promise.all([api('/api/network'),api('/api/metrics')]);paths=network.paths||[];metricsReady=true;$('mae').textContent=`${metrics.test_mae_s.toFixed(1)} с`;$('baseline').textContent=`${metrics.persistence_mae_s.toFixed(1)} с`;await refresh()}catch(error){$('notice').textContent=error.message;await refresh()}})();
updateControls();$('wall-clock').textContent=new Date().toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow'});
